// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8t_elrUe_BNMxF9Uyob-0zUgFDNwb-DE',
    appId: '1:674745280675:web:cff88d2b839b73f2333716',
    messagingSenderId: '674745280675',
    projectId: 'ivfcr-43a7f',
    authDomain: 'ivfcr-43a7f.firebaseapp.com',
    storageBucket: 'ivfcr-43a7f.appspot.com',
    measurementId: 'G-FN5RVGRBCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm6cQ0PcYuJxDSYqqAMQdO6NdhoICUDxA',
    appId: '1:674745280675:android:126891dc83e13414333716',
    messagingSenderId: '674745280675',
    projectId: 'ivfcr-43a7f',
    storageBucket: 'ivfcr-43a7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-V5Ykd2bLFouXt65gnUjoVYX-OvwddWM',
    appId: '1:674745280675:ios:9125cf3db2a314a6333716',
    messagingSenderId: '674745280675',
    projectId: 'ivfcr-43a7f',
    storageBucket: 'ivfcr-43a7f.appspot.com',
    iosClientId: '674745280675-3fr384q03d0ebrm1ip6pqg51v8jio018.apps.googleusercontent.com',
    iosBundleId: 'com.example.interactiveVoiceForCookingRecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-V5Ykd2bLFouXt65gnUjoVYX-OvwddWM',
    appId: '1:674745280675:ios:9125cf3db2a314a6333716',
    messagingSenderId: '674745280675',
    projectId: 'ivfcr-43a7f',
    storageBucket: 'ivfcr-43a7f.appspot.com',
    iosClientId: '674745280675-3fr384q03d0ebrm1ip6pqg51v8jio018.apps.googleusercontent.com',
    iosBundleId: 'com.example.interactiveVoiceForCookingRecipes',
  );
}
